name: Code checks

on:
  push:
    branches: [ master, tikkoeva, test]
  pull_request: 
    branches: [ master, tikkoeva, test]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.8' # the latest available version of PyPy that supports Python 3.6
        - '3.9' # the latest available version of PyPy that supports Python 3.7
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
    - name: Install Dependencies
      run: |
        pip install mypy
    - name: mypy
      run: |
        mypy .
